### ISSUE TITLE
argument string $$ changed to number

### ISSUE THREAD

**Issue by bezil** [lpil/argv#2]
gleam run is_alphanumeric $$
```
case argv.load().arguments {
    ["is_alphanumeric", input] -> {
      io.println(input) # getting 56604 instead of $$
    }
}
```
<img width="473" alt="Screenshot 2024-03-16 at 5 20 28 PM" src="https://github.com/lpil/argv/assets/16682429/6906962b-d897-4a7a-95f4-e23fa5622270">
<img width="543" alt="Screenshot 2024-03-16 at 5 20 41 PM" src="https://github.com/lpil/argv/assets/16682429/8c551d10-621a-45a4-aa1f-bdae500677a5">

**Comment by lpil** [comment]
How weird! Thank you

**Comment by bezil** [comment]
> How weird! Thank you

 Apparently In Unix-like shells, including Bash, the $$ variable represents the process ID (PID) of the current shell.
wrapping $$ inside single quote like this '$$' solved issue.

<img width="555" alt="Screenshot 2024-03-16 at 10 50 39 PM" src="https://github.com/lpil/argv/assets/16682429/cd62420c-169c-4dc4-8a82-49691a6c0390">

**Comment by lpil** [comment]
Ah! Mystery solved. Thank you
